# Partie permettant la generation d'un .jar
FROM maven:3-eclipse-temurin-21-alpine as maven
WORKDIR /app
COPY . .
RUN mvn clean package


FROM eclipse-temurin:21-jre-alpine  	

WORKDIR /usr/src/app

COPY --from=maven /app/target/backend-0.0.1-SNAPSHOT.jar .

CMD ["java","-jar","backend-0.0.1-SNAPSHOT.jar"]