name: Test and build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  DOCKER_USERNAME: nologin #login pour se co au depot du prof

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"
          cache: "maven"

      - name: Test with Maven
        run: mvn -B clean test --file pom.xml #Il sait auto que pom.xml est a la racine / -B enleve interaction humaine pour l'install

      - name: Build with Maven
        run: mvn -B package --file pom.xml # On build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/polytech2024
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.gha
          push: true
          tags: rg.fr-par.scw.cloud/polytech2024/vremy/backend:v1
